### ISSUE TITLE
Mac Mini with Sonoma 14.7: most games give blank or no windows

### ISSUE THREAD

**Issue by susan-davis** [angstsmurf/spatterlight#96] opened 2024-11-02 05:44 UTC
Attempting to play any game usually gives either no window and no feedback at all, or a small blank grey window. I've gotten two Glulx games to come up, but when I exited and tried to get back into them, I get the same behaviour, and there's no apparent pattern to when I can successfully launch something. The app is essentially unusable.

**Comment by susan-davis** [comment] 2024-11-02 05:44
(I do get a notification when I try to shut down the app about the games I launched still "running.")

**Comment by angstsmurf** [comment] 2024-11-02 06:57
Sorry to hear that. I've had similar reports in the past (see  #32) but I haven't found a reliable fix or way to reproduce it. My best guess is that it is caused by a failed autorestore.

I added some extra checks for autorestore failure to the test build at https://github.com/angstsmurf/spatterlight/releases/tag/v1.2.6.3b. It would be great if could try that version. If that doesn't work, you might be able to help me fix the problem by sharing your autosave data with me. It should be in one of the folders listed in this forum post: https://intfiction.org/t/spatterlight-1-1-released/62378/8. Just zip it up and put it here or [mail it to me](mailto:ignalina@me.com).

Otherwise, there are several suggestions in [the other issue report](https://github.com/angstsmurf/spatterlight/issues/32) and [the forum thread](https://intfiction.org/t/spatterlight-1-1-released/62378/8): deleting the saved application state, deleting the autosave files for individual games, removing the games from the library and re-adding them, and so on.

**Comment by angstsmurf** [comment] 2024-11-02 07:41
Some other things to try that just occurred to me:

- Switching off Autosave and autorestore in Settings > Misc and then quitting and restarting Spatterlight.
- Re-enabling the "This game was autorestored" warning with Settings > Global > Reset "Don't ask again" warnings, quitting and restarting Spatterlight, and then choosing Restart from any dialogs that show up.

**Comment by angstsmurf** [comment] 2024-11-10 11:18
Did any of this help?

**Comment by cspiegel** [comment] 2024-11-14 23:13
I wonder if there's _any_ relation to garglk/garglk#903.  I would imagine not, but just in case, I'll put this here to link the issues so we can at least keep track of any possible fixes in both projects.

**Comment by angstsmurf** [comment] 2024-11-15 19:27
Glad to head that!

Spatterlight tries to save bookmarks of all file permissions given, so in theory, you would only have to give it permission to access the files once. I have a hunch that keeping them on an external drive complicates matters, though.

**Comment by susan-davis** [comment] 2024-11-15 20:44
My internal drive is tiny, so most of my home directory lives on an external drive.

Just to keep a record of the conversation over on intfiction.org, my (new) current behaviour is that I can only launch new games if a game that I've already played is currently running.

**Comment by angstsmurf** [comment] 2024-11-20 05:51
I'd like to try to replicate your setup in order to fix this, but I'm having a little trouble getting started. What do I need to do for files on an external drive to appear in the `~Library/CloudStorage/Dropbox/` directory?

**Comment by angstsmurf** [comment] 2024-11-26 01:48
I've made a new test build here:
https://github.com/angstsmurf/spatterlight/releases/download/v1.2.9b/Spatterlight.zip

My hope is that this might help resolve your issues.

**Comment by susan-davis** [comment] 2024-11-26 21:22
Unable to reproduce the issue on this build! Yay!

**Comment by angstsmurf** [comment] 2024-11-27 03:24
Hopefully we can close this.

**Closed by angstsmurf** 2024-11-27 03:24 UTC
