### ISSUE TITLE
Corners in new windows have an unsightly white region until resized

### ISSUE THREAD

**Issue by agustincordes** [angstsmurf/spatterlight#7] opened 2020-04-22 14:43 UTC
All new windows (including the library) have this issue until they're resized in some way.
<img width="520" alt="Screen Shot 2020-04-22 at 11 41 55" src="https://user-images.githubusercontent.com/1068696/79996131-73b9cb80-848e-11ea-84c5-c332bf31f276.png">

**Comment by angstsmurf** [comment] 2020-04-22 15:10
I had those too for a while, but now I can't reproduce it any more. What OS are you on?

**Comment by megadr01d** [comment] 2020-04-22 15:16
Probably related to https://github.com/electron/electron/issues/517 with a [fix](https://github.com/electron/electron/pull/1441).

**Comment by angstsmurf** [comment] 2020-04-22 16:41
Thanks! It is still not clear to me what causes the problem or how to test it, but I guess I could set all windows to be non-opaque, even if it is supposed to be bad for performance.

It would be cool to have actual transparent windows like in Terminal or Zoom, though.

**Comment by megadr01d** [comment] 2020-04-22 16:51
Forgot to add that I think this only happens in the latest macOS versions. I'm on OS X 10.11 (El Capitan) and I don't suffer from this issue.

**Comment by angstsmurf** [comment] 2020-04-22 18:09
I've tried to reproduce it on 10.7, 10.8, 10.9, 10.14 and 10.15 without success, so I guess it only occurs under very specific conditions.

**Comment by agustincordes** [comment] 2020-04-22 18:36
I'm running Catalina 10.15.4. I'll be glad to help testing.

**Comment by angstsmurf** [comment] 2020-04-22 19:28
It seems I have no good solution for temporary file upload, so I'm abusing the Github release function. Perhaps you could try out [these three builds](https://github.com/angstsmurf/spatterlight/releases/tag/0.5.12test) and see if the problem is still there?

**Comment by agustincordes** [comment] 2020-04-22 20:31
**Spatterlight_upgraded_nibs** and **Spatterlight_not_opaque** throw an "Application is damaged" error, probably because they aren't notarized. But I'm happy to report that **Spatterlight_notarized_10.15_only** works well. There's even another UI error that I didn't report that got fixed in this build.

This happens in 0.5.12b when the menu bar is shown while in fullscreen: 

<img width="2560" alt="Screen Shot 2020-04-22 at 17 28 13" src="https://user-images.githubusercontent.com/1068696/80030754-05413180-84bf-11ea-8cb3-af5dc3d60263.png">

And it's now fixed in the 10.15 build:

<img width="2560" alt="Screen Shot 2020-04-22 at 17 27 52" src="https://user-images.githubusercontent.com/1068696/80030789-112cf380-84bf-11ea-9200-7b661a40e8f6.png">

**Comment by angstsmurf** [comment] 2020-04-22 22:11
Thanks for trying them out! Well, at least we know that targeting the 10.15 SDK fixes this particular problem. I'll do the lazy thing and just add that version to the other two for now.

**Comment by agustincordes** [comment] 2020-04-22 22:17
No complains 😄 

I'll try to contribute with some tweaks as soon as I can!

**Comment by angstsmurf** [comment] 2020-04-22 22:23
That would be great!

By the way, the reason I didn't see these glitches on Catalina was probably that I run it in a VM, without hardware graphics acceleration. Perhaps I should just bite the bullet and upgrade to Catalina.

**Comment by agustincordes** [comment] 2020-04-23 00:48
It works pretty well, I'd say it's a mandatory upgrade at this point!

**Comment by megadr01d** [comment] 2020-04-23 12:24
> I'd say it's a mandatory upgrade at this point!

Unless you're on old hardware and can't update anymore past 10.11. :/

**Comment by angstsmurf** [comment] 2020-11-22 23:30
Update: I've upgraded to Catalina 10.15.7 and I can't reproduce this problem, which hopefully means it is fixed now.

**Closed by angstsmurf** 2020-11-22 23:30 UTC
